# Generated by Django 3.2.9 on 2021-11-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=40)),
                ('lastName', models.CharField(max_length=40)),
                ('dateOfBirth', models.DateField()),
                ('address', models.TextField(max_length=40)),
                ('phoneNumber', models.TextField(max_length=15)),
                ('email', models.EmailField(max_length=40)),
                ('socialSecurity', models.TextField(max_length=9)),
            ],
        ),
    ]
